apiVersion: ngergs.de/v1alpha1
kind: XConfig
metadata:
  name: example-configs
spec:
  template: Hello {world}, it's {timeOfDay}
  valueSets:
    - name: morning
      values:
        world: world
        timeOfDay: morning
    - name: evening
      values:
        world: world
        timeOfDay: evening
  claimRef:
    apiVersion: ngergs.de/v1alpha1
    kind: Config
    name: example-configs
    namespace: test