apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configs
spec:
  dependsOn:
    - apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: ${REGISTRY}/${FN_IMAGE}
      version: "=${FN_TAG}"
  crossplane:
    version: ">=v2.0.0"
