apiVersion: ngergs.de/v1alpha1
kind: Config
metadata:
  name: example-configs
  namespace: test
  generation: 3
spec:
  template: Hello {world}, it's {timeOfDay}
  valueSets:
    - name: morning
      values:
        world: world
        timeOfDay: morning
    - name: evening
      values:
        world: world
        timeOfDay: evening
