apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: configs.ngergs.de
spec:
  scope: Namespaced
  group: ngergs.de
  names:
    kind: Config
    plural: configs
  versions:
    - name: v1alpha1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                template:
                  type: string
                valueSets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      values:
                        type: object
                        additionalProperties:
                          type: string
                    required:
                      - name
                      - values
              required:
                - template
                - valueSets
            # must model a barebone status even if not interested to allow deserialize checks
            # to distinguish between crossplane internal `status.crossplane` and `status.conditions`
            # (which are fine to ignore as they are mapped to other fields in the protobuf schema)
            # and other spurious `status`-entries (that should cause errors)
            status:
              type: object
          required:
            - spec
