apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: configs.ngergs.de
spec:
  scope: Namespaced
  group: ngergs.de
  names:
    kind: Config
    plural: configs
  versions:
    - name: v1alpha1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                template:
                  type: string
                valueSets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      values:
                        type: object
                        additionalProperties:
                          type: string
                    required:
                      - name
                      - values
              required:
                - template
                - valueSets
          required:
            - spec
